### ISSUE TITLE
Open Issue: Terminology Missing

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/PCC.ODH#2]
There are MANY required terminology vocabulary that is not available. 
 
1. https://metadata.ilo.org/thesaurus.html
2. https://www.ilo.org/global/industries-and-sectors/health-services/lang--en/index.htm
3. http://terminology.hl7.org/CodeSystem/PHOccupationalDataForHealthODH
4. urn:oid:2.16.840.1.114222.4.5.327

**Comment by afourquet** [comment]
Terminology Added with permission of the International Labor Organization (ILO) to host the codes for the code system.
